# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: redis:latest
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/iguagile/iguagile-engine
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports && diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./lib/*")) <(printf "")
      - run: go get -u golang.org/x/lint/golint && golint -set_exit_status ./...
      - run: go vet -all -shadowstrict $(go list ./... | grep -v /vendor/ | grep -v /lib/)
      - run: go test -v ./...
#      - run: go get -u github.com/alecthomas/gometalinter
#      - run: gometalinter --install
#      - run: curl https://git.io/vp6lP | sh
#      - run: gometalinter ./...
